language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
install:
  - python setup.py install
script:
  - python -W always setup.py test
matrix:
  allow_failures:
    - python: "3.7-dev"
