language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - pip install "flake8>=2.0,<3.0" mock --use-mirrors
  - python setup.py install
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then flake8 delighted; fi
  - python -W always setup.py test
